name: Linters
on:
  pull_request:
    types: [ labeled ]

jobs:
  pronto:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: |
          git fetch --no-tags --prune origin +refs/heads/*:refs/remotes/origin/*
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        timeout-minutes: 10
        with:
          bundler-cache: true
      - name: Run StandardRB
        run: bundle exec standardrb
